[package]
name = "shutdown-button"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.0.0", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.20"
rust_gpiozero = "^0.2"
